### ISSUE TITLE
OPS/REXX Can't install on 17.9 of VScode

### ISSUE THREAD

**Issue by TrebucheterChris** [BroadcomMFD/opsrexx-language-support#1]
Question will it still be supported - I rely on so much

Did an install and got the following log:
3/15/2024 5:15:07 PM - Microsoft VSIX Installer
3/15/2024 5:15:07 PM - -------------------------------------------
3/15/2024 5:15:07 PM - vsixinstaller.exe version:
3/15/2024 5:15:07 PM - 17.9.3180+083a582996
3/15/2024 5:15:07 PM - -------------------------------------------
3/15/2024 5:15:07 PM - Command line parameters:
3/15/2024 5:15:07 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\cgero\Downloads\broadcomMFD.opsrexx-language-support-0.4.0(1).vsix
3/15/2024 5:15:07 PM - -------------------------------------------
3/15/2024 5:15:07 PM - Microsoft VSIX Installer
3/15/2024 5:15:07 PM - -------------------------------------------
3/15/2024 5:15:07 PM - Initializing Install...
3/15/2024 5:15:07 PM - Searching for applicable products...
3/15/2024 5:15:08 PM - Found installed product - Visual Studio Community 2022
3/15/2024 5:15:08 PM - Found installed product - Global Location
3/15/2024 5:15:08 PM - Extension Details...
3/15/2024 5:15:08 PM - 	Identifier         : opsrexx-language-support
3/15/2024 5:15:08 PM - 	Name               : OPS/REXX Language Support
3/15/2024 5:15:08 PM - 	Author             : broadcomMFD
3/15/2024 5:15:08 PM - 	Version            : 0.4.0
3/15/2024 5:15:08 PM - 	Description        : OPS/REXX Language Support Visual Studio Code Extension
3/15/2024 5:15:08 PM - 	Locale             : en-US
3/15/2024 5:15:08 PM - 	MoreInfoURL        : 
3/15/2024 5:15:08 PM - 	InstalledByMSI     : False
3/15/2024 5:15:08 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
3/15/2024 5:15:08 PM - 	SignatureState     : Unsigned
3/15/2024 5:15:08 PM - 	Supported Products : 
3/15/2024 5:15:08 PM - 		Microsoft.VisualStudio.Code
3/15/2024 5:15:08 PM - 			Version : 
3/15/2024 5:15:08 PM - 			ProductArchitecture : x86
3/15/2024 5:15:08 PM - 	References         : 
3/15/2024 5:15:08 PM - Signature Details...
3/15/2024 5:15:08 PM - 	Extension is not signed.
3/15/2024 5:15:08 PM - VSIXInstaller.NoApplicableSKUsException: One or more extensions are for Visual Studio Code. Try installing them in Visual Studio Code.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by CraigFreiwald** [comment]
Hello,
It appears you are trying to install this [VS Code](https://code.visualstudio.com/) extension in [Microsoft Visual Studio](https://visualstudio.microsoft.com/).

Please try installing the downloaded .vsix file from within VS Code, or use the VS Code extension marketplace to search for and [install the extension](https://code.visualstudio.com/docs/editor/extension-marketplace).
